# Generated by Django 2.0.1 on 2018-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileunit',
            name='origin_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileunit',
            name='result_path',
            field=models.FileField(upload_to=''),
        ),
    ]
