# Generated by Django 2.0.1 on 2018-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0003_remove_fileunit_result_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileunit',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
