# Generated by Django 2.0.1 on 2018-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0004_fileunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileunit',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
