# Generated by Django 2.0.1 on 2018-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0008_auto_20180206_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
