# Generated by Django 2.0.1 on 2018-02-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0011_auto_20180206_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
