# Generated by Django 2.0.1 on 2018-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0012_remove_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
