# Generated by Django 2.0.1 on 2018-03-06 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0014_document_result_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='config_start',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
