# Generated by Django 2.0.1 on 2018-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0016_auto_20180306_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='num_machines',
            field=models.IntegerField(default=0),
        ),
    ]
